//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateProfessional
    {
        public int candidateProfId { get; set; }
        public Nullable<int> candidateId { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> experienceYears { get; set; }
        public Nullable<int> experienceMonth { get; set; }
        public Nullable<int> salary { get; set; }
        public string industry { get; set; }
        public string industryRole { get; set; }
        public string skills { get; set; }
        public string company { get; set; }
    }
}
