//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateBasic
    {
        public int candidateId { get; set; }
        public string username { get; set; }
        public Nullable<int> quesId { get; set; }
        public string ansr { get; set; }
        public Nullable<System.DateTime> profileDate { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string candidateAddr { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> contactNo { get; set; }
        public string emailId { get; set; }
        public string city { get; set; }
        public string resumePath { get; set; }
    }
}
