//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEducation
    {
        public int candidateEduId { get; set; }
        public Nullable<int> candidateId { get; set; }
        public string aLevelSubject1 { get; set; }
        public string aLevelSubject2 { get; set; }
        public string aLevelSubject3 { get; set; }
        public Nullable<int> aLevelGrade1 { get; set; }
        public Nullable<int> aLevelGrade2 { get; set; }
        public Nullable<int> aLevelGrade3 { get; set; }
        public string graduation { get; set; }
        public string instituteGrad { get; set; }
        public Nullable<decimal> percentageGrad { get; set; }
        public string postGrad { get; set; }
        public string institutePostGrad { get; set; }
        public Nullable<decimal> percentagePostGrad { get; set; }
        public string certification { get; set; }
    }
}
