//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int companyId { get; set; }
        public string companyName { get; set; }
        public string username { get; set; }
        public Nullable<int> quesId { get; set; }
        public string ansr { get; set; }
        public string contactPerson { get; set; }
        public Nullable<int> companyContact { get; set; }
        public string companyAddr { get; set; }
        public string companyEmail { get; set; }
        public string companyDetails { get; set; }
    }
}
