//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        public int jobPostId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> areaid { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<int> jobTitleId { get; set; }
        public string type { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> postedDate { get; set; }
        public string skillsReq { get; set; }
        public string educationReq { get; set; }
        public string description { get; set; }
        public string contactEmail { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<bool> isAvailable { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Category Category { get; set; }
        public virtual JobTitle JobTitle { get; set; }
    }
}
